### ISSUE TITLE
Password for product page fails

### ISSUE THREAD

**Issue by tommypepsi** [Shopify/lighthouse-ci-action#15]
I managed to use lighthouse ci for a live store but now I'm having issues with a password protected dev store. 

Home page works fine then it times out trying to get the password input for the product page.

here's the logs:
```
Getting a new page...
Getting password cookie...
Getting preview cookie...
Running Lighthouse 3 time(s) on https://***/?_fd=0&pb=0
Run #1...done.
Run #2...done.
Run #3...done.
Getting a new page...
Getting password cookie...
TimeoutError: waiting for selector `form[action*=password] input[type="password"]` failed: timeout 30000ms exceeded
    at new WaitTask (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:29)
    at Frame.waitForSelector (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51)
    at Page.waitForSelector (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2238:33)
    at module.exports (/github/workspace/setPreviewCookies.js:9:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async PuppeteerManager.invokePuppeteerScriptForUrl (/.node/lib/node_modules/@lhci/cli/src/collect/puppeteer-manager.js:108:5)

    at async Object.runCommand (/.node/lib/node_modules/@lhci/cli/src/collect/collect.js:240:7)
```

**Comment by charlespwd** [comment]
Oh, that's strage. Why would it work for the homepage but not the product page?

Do you have a custom password page? The puppetteer script assumes that there's a `<form action="/password">` on the page with a `<input type="password">` password field and the error seems to indicate that it's unable to find that.

Can't guess why it would behave differently starting from the product page. Some kind of redirect?

Would you consent to allow me to inspect your store to debug? If yes, please send me the shop URL by at cp.clermont@shopify.com and I'll take a look.
