### ISSUE TITLE
Lighthouse looking for password somewhere on clean Dawn theme

### ISSUE THREAD

**Issue by Avex-Dev** [Shopify/lighthouse-ci-action#33]
I am working right off a download of a clean Dawn theme following https://shopify.dev/themes/getting-started/create which has a password page, however, the password is not active, and I am getting the following error:

```
Configuring shopify CLI
Will run Lighthouse CI on https://***
==============================
Creating development theme
{"theme":{"id":128112328866,"name":"Development (a77b97-d351661ce68d)","role":"development","shop":"***","editor_url":"https://***/admin/themes/128112328866/editor","preview_url":"https://***/?preview_theme_id=128112328866"}}
==============================
Configuring Lighthouse CI
==============================
Running Lighthouse CI
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
✅  GitHub token set
Healthcheck passed!

Getting a new page...
Getting password cookie...
TimeoutError: waiting for selector `form[action*=password] input[type="password"]` failed: timeout 30000ms exceeded
    at new WaitTask (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:29)
    at Frame.waitForSelector (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51)
    at Page.waitForSelector (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2238:33)
    at module.exports (/github/workspace/setPreviewCookies.js:9:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async PuppeteerManager.invokePuppeteerScriptForUrl (/.node/lib/node_modules/@lhci/cli/src/collect/puppeteer-manager.js:108:5)

    at async Object.runCommand (/.node/lib/node_modules/@lhci/cli/src/collect/collect.js:240:7)
```

_Originally posted by @Avex-Dev in https://github.com/Shopify/lighthouse-ci-action/issues/15#issuecomment-1004291159_

**Comment by govrayt** [comment]
Hey @Avex-Dev I've worked out how to fix this...

If your store isn't password protected (via Shopify Admin) - don't set the 'SHOP_PASSWORD' secret in your repo, this will then bypass the password page check in lighthouse check.

It would also help if Shopify updated their documentation to explain this!

The below explains why...

`  if ('$shop_password' !== '') {
    console.error('Getting password cookie...');
    await page.goto('$host/password');
    await page.waitForSelector('form[action*=password] input[type="password"]');
    await page.\$eval('form[action*=password] input[type="password"]', input => input.value = '$shop_password');
    await Promise.all([
      page.waitForNavigation(),
      page.\$eval('form[action*=password]', form => form.submit()),
    ])
  }`

**Comment by Adnandeardigital** [comment]
Hey guys, I'm also facing the same issue. In my case, I have a development store, and it's password-protected. I've added the correct password, but I'm still getting the following error log. Has this issue been resolved by any chance? or this is only for stores that are not having password protection ? 🤔 

```
==============================
Running Lighthouse CI
✅  .lighthouseci/ directory writable
✅  Configuration file found
✅  Chrome installation found
✅  GitHub token set
Healthcheck passed!

Getting a new page...
Getting password cookie...
Getting preview cookie...
Running Lighthouse 3 time(s) on https://***/?preview_theme_id=16[25](https://github.com/Adnandeardigital/another-shopify-repo/actions/runs/6561257071/job/17821113831#step:4:26)73812014&_fd=0&pb=0
Run #1...done.
Run #2...done.
Getting a new page...
Run #3...done.
Getting password cookie...
TimeoutError: waiting for selector `form[action*=password] input[type="password"]` failed: timeout 30000ms exceeded
    at new WaitTask (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:[26](https://github.com/Adnandeardigital/another-shopify-repo/actions/runs/6561257071/job/17821113831#step:4:27))
    at Object.internalHandler.waitFor (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:[29](https://github.com/Adnandeardigital/another-shopify-repo/actions/runs/6561257071/job/17821113831#step:4:30))
    at Frame.waitForSelector (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51)
    at Page.waitForSelector (/.node/lib/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2238:[33](https://github.com/Adnandeardigital/another-shopify-repo/actions/runs/6561257071/job/17821113831#step:4:34))
    at module.exports (/github/workspace/setPreviewCookies.js:9:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async PuppeteerManager.invokePuppeteerScriptForUrl (/.node/lib/node_modules/@lhci/cli/src/collect/puppeteer-manager.js:108:5)

    at async Object.runCommand (/.node/lib/node_modules/@lhci/cli/src/collect/collect.js:2[40](https://github.com/Adnandeardigital/another-shopify-repo/actions/runs/6561257071/job/17821113831#step:4:41):7)
```

**Comment by charlespwd** [comment]
This error is shown when there isn't a form with an input of type password on your theme. e.g.
```
<form action="...password">
  <input type="password">
</form>
```

Did any of you change it? Did the platform change it? The above code made the assumption that this would be there on the password page.

**Comment by eddysims** [comment]
Can also confirm that my store has a password with the proper elements:

![image](https://github.com/Shopify/lighthouse-ci-action/assets/46460840/09ab041a-17c5-4ead-805b-eca14d965ad5)

and

![image](https://github.com/Shopify/lighthouse-ci-action/assets/46460840/a8d3d6d7-0e2c-4fc4-ad5b-da340854f9d6)

**Comment by jgiordanoGG** [comment]
Not sure if anyone else has seen a change today, but just as suddenly and inexplicably as this stopped working last week it started working again this morning. We haven't made any changes that I can imagine would impact this at all — certainly no changes to the password form since it's not something we have access to. Either way, just really grateful to see that little green checkmark again 😆 

<img width="315" alt="image" src="https://github.com/Shopify/lighthouse-ci-action/assets/24391453/2d86582f-9213-4c49-a8cd-368147db0627">

**Comment by jgiordanoGG** [comment]
No worries at all @charlespwd , and thanks for the additional info here! I appreciate you closing the loop for us!

**Comment by fergus-haywood** [comment]
Was this issue ever resolved? I'm using v.1.2.1, however still getting the same TimeOut error:

```TimeoutError: Waiting for selector `form[action*=password] input[type="password"]` failed: Waiting failed: 30000ms exceeded```
