### ISSUE TITLE
Error: Protocol error (Page.navigate): Cannot navigate to invalid URL

### ISSUE THREAD

**Issue by jeremymcclelland** [Shopify/lighthouse-ci-action#58]
Running into this issue with our action. The code base requires yarn build to compile all of our assets, sections, and snippets so I would bet it is because our repo does not follow the standard shopify theme structure.

<img width="1266" alt="Screen Shot 2023-03-07 at 7 31 10 PM" src="https://user-images.githubusercontent.com/7494166/223587966-55ab22b1-fdfd-4da6-b138-86ffa312180d.png">

**Comment by bincani** [comment]
just started for me on shopify previews 

```
ProtocolError: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at <instance_members_initializer> (/.node/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:86:14)
    at new Callback (/.node/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:90:16)
    at CallbackRegistry.create (/.node/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
    at Connection._rawSend (/.node/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:80:26)
    at CdpCDPSession.send (/.node/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)
    at navigate (/.node/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:1[59](https://github.com/fxdevelopers/shopify-theme-sunrise/actions/runs/12170845482/job/33946614691#step:8:60):51)
    at CdpFrame.goto (/.node/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:137:17)
    at CdpFrame.<anonymous> (/.node/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
    at CdpPage.goto (/.node/lib/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:592:43)

    at module.exports (/github/workspace/setPreviewCookies.js:18:14)
```

**Comment by graygilmore** [comment]
Hey folks! We're going to close this one for now as this doesn't appear to be a long-term problem but rather something that can bubble up occasionally due to GitHub's CI. If you run into this problem again and it is reproducible please fire up a new issue and we can have a look at it.
